### ISSUE TITLE
All endpoints but Skill Queue disabled

### ISSUE THREAD

**Issue by ehawman** [mgoeppner/evemon#64]
![image](https://github.com/mgoeppner/evemon/assets/52979227/5cee11b1-cffb-4106-9e09-5908d19201c6)

When first adding the character via ESI I get the current ship, current wallet balance, current everything. However, it appears that after this initial sync those values never update. Most notably my wallet values on one character (that I didn't delete/re-add) are 36hrs out of date. Is this something specific to my installation? 4.2.2

**Comment by mgoeppner** [comment]
This is working as originally designed -- you need to enable the ones you want via this drop down on the character sheet:

![bild](https://github.com/mgoeppner/evemon/assets/1063646/933b01cb-51df-4729-86ce-906a9adfbdc8)

Since wallet polling is disabled, it would have only updated on first run, which is likely why it is out of date.
